CREATE TABLE [Production].[Product] (

	[ProductID] int NULL, 
	[Name] varchar(100) NULL, 
	[ProductNumber] varchar(50) NULL, 
	[MakeFlag] varchar(200) NULL, 
	[FinishedGoodsFlag] varchar(200) NULL, 
	[Color] varchar(30) NULL, 
	[SafetyStockLevel] smallint NULL, 
	[ReorderPoint] smallint NULL, 
	[StandardCost] decimal(19,4) NULL, 
	[ListPrice] decimal(19,4) NULL, 
	[Size] varchar(10) NULL, 
	[SizeUnitMeasureCode] varchar(6) NULL, 
	[WeightUnitMeasureCode] varchar(6) NULL, 
	[Weight] decimal(18,4) NULL, 
	[DaysToManufacture] int NULL, 
	[ProductLine] varchar(4) NULL, 
	[Class] varchar(4) NULL, 
	[Style] varchar(4) NULL, 
	[ProductSubcategoryID] int NULL, 
	[ProductModelID] int NULL, 
	[SellStartDate] datetime2(6) NULL, 
	[SellEndDate] datetime2(6) NULL, 
	[DiscontinuedDate] datetime2(6) NULL, 
	[rowguid] varchar(40) NULL, 
	[ModifiedDate] datetime2(6) NULL
);