table camera_company_dataset
	lineageTag: f3363ebd-ffcb-48b7-98d2-4d9bd2c9658f

	measure 'Average Sales per Day' = AVERAGE(camera_company_dataset[Gross Sales])
		lineageTag: 09cb853d-3e78-4aa9-95ca-85deb2a32493

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3feb3cd4-7653-40c0-bc90-13f2b6b0825a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Buyer Type'
		dataType: string
		lineageTag: d86bf5ce-4ba3-4a49-881b-e55642fa0973
		summarizeBy: none
		sourceColumn: Buyer Type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: edfc0795-be9a-4c67-b2b4-86276fd24b63
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 45184b51-5bd6-4352-a7ec-f4c80c75c1f6
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 9c6504ea-ae1c-426c-b6e2-04b7a1b37c95
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: 622f6722-2237-4fe3-868a-1b7260845d05
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price'
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3d40242e-ce6b-4c72-bef3-9dc18205a89e
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = User

	column 'Sale Price'
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 193b71f5-8560-4e79-8fee-8c18a2fd88df
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Gross Sales'
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8f871555-93e7-4367-8408-334a30415f05
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

	column 'Discount Value'
		dataType: int64
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 736d4eed-0429-477c-9ba2-8e251bdc7d15
		summarizeBy: sum
		sourceColumn: Discount Value

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Net Sales'
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e0ad4a7e-d378-41b8-b9b3-1180ddf43144
		summarizeBy: sum
		sourceColumn: Net Sales

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 02217412-d2b0-4df2-bef5-4ec8e1afd6f4
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

	column profit
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6ab0892e-f1f1-46ff-b920-7eae14473420
		summarizeBy: sum
		sourceColumn: profit

		annotation SummarizationSetBy = Automatic

	partition camera_company_dataset = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=PostgreSQL35W", [HierarchicalNavigation=true]),
				    bfxpostgresql_Database = Source{[Name="bfxpostgresql",Kind="Database"]}[Data],
				    public_Schema = bfxpostgresql_Database{[Name="public",Kind="Schema"]}[Data],
				    camera_calendar_csv_Table = public_Schema{[Name="camera_calendar_csv",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(camera_calendar_csv_Table,{{"Discount Type", "Discount Value"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

