table 'Boomi Process Monitoring'
	lineageTag: 2fde481f-0d21-430c-94e4-3cc2b0c1f850

	measure occ1 = SUM('Boomi Process Monitoring'[Occurence ])+0
		formatString: 0
		lineageTag: 0127cb76-89c9-47f6-b829-58bfaa64a53f

	column 'S.NO'
		dataType: int64
		formatString: 0
		lineageTag: f4b62655-3162-49bd-8000-759484261922
		summarizeBy: sum
		sourceColumn: S.NO

		annotation SummarizationSetBy = Automatic

	column 'Reported Date(PST)'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bf43ec62-e71e-4893-85b5-2a39b4b44e70
		summarizeBy: none
		sourceColumn: Reported Date(PST)

		variation Variation
			isDefault
			relationship: f4281092-6e65-4192-92f2-846eb625eace
			defaultHierarchy: LocalDateTable_7726cbe5-9c2c-47c1-8e4a-5ed064980120.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Received Date(PST) '
		dataType: dateTime
		formatString: Long Date
		lineageTag: ad8b2d93-c054-4d93-9035-723b77e2caa1
		summarizeBy: none
		sourceColumn: "Received Date(PST) "

		variation Variation
			isDefault
			relationship: 13964fc9-8223-407c-ae71-c57792bd144f
			defaultHierarchy: LocalDateTable_7211c870-d960-4503-af6f-9536fe6001eb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProcessId
		dataType: string
		lineageTag: cffe1017-d0e0-496b-ac34-f0f7a796cf69
		summarizeBy: none
		sourceColumn: ProcessId

		annotation SummarizationSetBy = Automatic

	column ProcessName
		dataType: string
		lineageTag: 69943f2e-1d70-4fb4-a5bd-1fe01d5ab0bd
		summarizeBy: none
		sourceColumn: ProcessName

		annotation SummarizationSetBy = Automatic

	column 'Playbook ID     '
		dataType: string
		lineageTag: 72d36ba3-da3a-41b2-8f35-a4488a7ff0da
		summarizeBy: none
		sourceColumn: "Playbook ID     "

		annotation SummarizationSetBy = Automatic

	column 'Failure / Error Time in PST'
		dataType: string
		lineageTag: 31424df1-a660-4c05-a0b4-fac9bb317c87
		summarizeBy: none
		sourceColumn: Failure / Error Time in PST

		annotation SummarizationSetBy = Automatic

	column 'Error Message'
		dataType: string
		lineageTag: 2b3e71f5-b75a-4d85-bf2e-e34da09d2301
		summarizeBy: none
		sourceColumn: Error Message

		annotation SummarizationSetBy = Automatic

	column 'Action(In Playbook)'
		dataType: string
		lineageTag: 057f3396-2eac-495b-a825-4fdd8ee4103c
		summarizeBy: none
		sourceColumn: Action(In Playbook)

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 8ba3e4dd-90dc-4848-bbda-517dc12c6ad8
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column 'In Playbook'
		dataType: string
		lineageTag: 4818539f-45d6-4c02-919a-b7a1894a4b42
		summarizeBy: none
		sourceColumn: In Playbook

		annotation SummarizationSetBy = Automatic

	column 'Occurence '
		dataType: int64
		formatString: 0
		lineageTag: 32bcc943-4d09-45c4-8f59-64594c689973
		summarizeBy: sum
		sourceColumn: "Occurence "

		annotation SummarizationSetBy = Automatic

	column 'Process Reporting URL'
		dataType: string
		lineageTag: c3b0053b-21f1-4071-af2f-4f6f680627a8
		summarizeBy: none
		sourceColumn: Process Reporting URL

		annotation SummarizationSetBy = Automatic

	column 'Action Taken'
		dataType: string
		lineageTag: a99f8731-d11f-418a-b80f-d2c4add0c029
		summarizeBy: none
		sourceColumn: Action Taken

		annotation SummarizationSetBy = Automatic

	column Folder
		dataType: string
		lineageTag: 07a6a900-7aaa-4218-bd54-dcf6dad6b70b
		summarizeBy: none
		sourceColumn: Folder

		annotation SummarizationSetBy = Automatic

	column 'Analysis '
		dataType: string
		lineageTag: ebc6db33-3e9b-4d8d-be7a-c8666b880849
		summarizeBy: none
		sourceColumn: "Analysis "

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: fddda5f4-0fc3-4007-9997-92a1ecfcffb7
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column 'Scheduled type'
		dataType: string
		lineageTag: ffe480b4-75da-405f-9e56-3d0b3149f86e
		summarizeBy: none
		sourceColumn: Scheduled type

		annotation SummarizationSetBy = Automatic

	column 'Error Type'
		dataType: string
		lineageTag: d2c5fbfb-9597-41f5-b859-8d207ffe4538
		summarizeBy: none
		sourceColumn: Error Type

		annotation SummarizationSetBy = Automatic

	column 'Error Name'
		dataType: string
		lineageTag: 0ffc60f9-e198-444e-b048-4ac7c71504f1
		summarizeBy: none
		sourceColumn: Error Name

		annotation SummarizationSetBy = Automatic

	column 'End Point'
		dataType: string
		lineageTag: e6f1bece-7358-4ed2-b52a-8357a8ea2331
		summarizeBy: none
		sourceColumn: End Point

		annotation SummarizationSetBy = Automatic

	column Connector
		dataType: string
		lineageTag: 2e216d09-679b-484a-aaa5-cdf1463eb20f
		summarizeBy: none
		sourceColumn: Connector

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: 9bc4aab9-52ac-4afd-859d-d67902149f97
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column 'Start time'
		dataType: dateTime
		formatString: General Date
		lineageTag: a59899d0-e253-4e9d-92ab-dc774c4b005a
		summarizeBy: none
		sourceColumn: Start time

		variation Variation
			isDefault
			relationship: dbcb3e0c-c315-409a-84f0-6ef3da1232f6
			defaultHierarchy: LocalDateTable_e9cc24cb-9acf-4e57-90c3-c99f7bc05012.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'End time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0acf8e9b-54cd-45cd-a38e-fc69deab5751
		summarizeBy: none
		sourceColumn: End time

		variation Variation
			isDefault
			relationship: f180993b-73a4-4cf0-93d5-28b0b033b0ff
			defaultHierarchy: LocalDateTable_f93ed65f-9aa5-41b4-910f-3be05f01c8b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'ProcessName - Copy.1'
		dataType: string
		lineageTag: 0a64b147-5b0e-43f0-b75c-80d27bb226eb
		summarizeBy: none
		sourceColumn: ProcessName - Copy.1

		annotation SummarizationSetBy = Automatic

	column 'short name 22'
		dataType: string
		lineageTag: 9725e4b4-668c-4a3a-aa58-1cc2a740f49e
		summarizeBy: none
		sourceColumn: short name 22

		annotation SummarizationSetBy = Automatic

	partition 'Boomi Process Monitoring' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bloomfieldx.sharepoint.com/sites/SkxBoomiSupport/Shared%20Documents/Report%20Generating%20Dashbaords/Boomi%20Daily%20Report/Boomi%20Realtime%20Dashboard_Daily_email.xlsx"), null, true),
				    #"Boomi Process Monitoring_Sheet" = Source{[Item="Boomi Process Monitoring",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Boomi Process Monitoring_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"S.NO", Int64.Type}, {"Reported Date(PST)", type date}, {"Received Date(PST) ", type date}, {"ProcessId", type text}, {"ProcessName", type text}, {"Playbook ID     ", type text}, {"Failure / Error Time in PST", type text}, {"Error Message", type text}, {"Action(In Playbook)", type text}, {"Criticality", type text}, {"In Playbook", type text}, {"Occurence ", Int64.Type}, {"Process Reporting URL", type text}, {"Action Taken", type text}, {"Folder", type text}, {"Analysis ", type text}, {"Comments", type text}, {"Scheduled type", type text}, {"Error Type", type text}, {"Error Name", type text}, {"End Point", type text}, {"Connector", type text}, {"Action", type text}, {"Start time", type datetime}, {"End time", type datetime}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "ProcessName", "ProcessName - Copy"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Column", "ProcessName - Copy", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"ProcessName - Copy.1", "ProcessName - Copy.2", "ProcessName - Copy.3"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"ProcessName - Copy.1", type text}, {"ProcessName - Copy.2", type text}, {"ProcessName - Copy.3", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"ProcessName - Copy.2", "ProcessName - Copy.3"}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Removed Columns", "ProcessName", "ProcessName - Copy"),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Duplicated Column1", "ProcessName - Copy", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"ProcessName - Copy.1.1", "ProcessName - Copy.2", "ProcessName - Copy.3"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"ProcessName - Copy.1.1", type text}, {"ProcessName - Copy.2", type text}, {"ProcessName - Copy.3", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type2",{"ProcessName - Copy.2", "ProcessName - Copy.3", "ProcessName - Copy.1.1"}),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Removed Columns1", "ProcessName", "ProcessName - Copy"),
				    #"Split Column by Position" = Table.SplitColumn(#"Duplicated Column2", "ProcessName - Copy", Splitter.SplitTextByRepeatedLengths(22), {"ProcessName - Copy.1.1", "ProcessName - Copy.2", "ProcessName - Copy.3"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Split Column by Position",{"ProcessName - Copy.2", "ProcessName - Copy.3"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns3",{{"ProcessName - Copy.1.1", "short name 22"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

