CREATE TABLE [Sales].[SalesOrderHeader] (

	[SalesOrderID] int NULL, 
	[RevisionNumber] smallint NULL, 
	[OrderDate] datetime2(6) NULL, 
	[DueDate] datetime2(6) NULL, 
	[ShipDate] datetime2(6) NULL, 
	[Status] smallint NULL, 
	[OnlineOrderFlag] varchar(200) NULL, 
	[SalesOrderNumber] varchar(50) NULL, 
	[PurchaseOrderNumber] varchar(50) NULL, 
	[AccountNumber] varchar(30) NULL, 
	[CustomerID] int NULL, 
	[SalesPersonID] int NULL, 
	[TerritoryID] int NULL, 
	[BillToAddressID] int NULL, 
	[ShipToAddressID] int NULL, 
	[ShipMethodID] int NULL, 
	[CreditCardID] int NULL, 
	[CreditCardApprovalCode] varchar(15) NULL, 
	[CurrencyRateID] int NULL, 
	[SubTotal] decimal(19,4) NULL, 
	[TaxAmt] decimal(19,4) NULL, 
	[Freight] decimal(19,4) NULL, 
	[TotalDue] decimal(19,4) NULL, 
	[Comment] varchar(256) NULL, 
	[rowguid] varchar(40) NULL, 
	[ModifiedDate] datetime2(6) NULL
);